//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mass_Data_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int Id { get; set; }
        public string PersonID { get; set; }
        public int PaidForMonth { get; set; }
        public int PaidForYear { get; set; }
        public System.DateTime PayDate { get; set; }
        public int Amount { get; set; }
        public int PaymantNamesId { get; set; }
        public int Deleted { get; set; }
    
        public virtual PaymantNames PaymantNames { get; set; }
        public virtual Person Person { get; set; }
    }
}
