//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mass_Data_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int Id { get; set; }
        public string PersonID { get; set; }
        public int InstituteID { get; set; }
        public Nullable<int> ReferencePersonNameId { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Institute Institute { get; set; }
        public virtual Person Person { get; set; }
    }
}
