//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mass_Data_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int Id { get; set; }
        public string PersonId { get; set; }
        public string TableName { get; set; }
        public int TableRowID { get; set; }
        public string DataLog { get; set; }
        public System.DateTime Date { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
