//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mass_Data_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Accounting = new HashSet<Accounting>();
            this.Admission = new HashSet<Admission>();
            this.Institute = new HashSet<Institute>();
            this.LogData = new HashSet<LogData>();
            this.Result = new HashSet<Result>();
            this.StudentAttendance = new HashSet<StudentAttendance>();
            this.StudentClass = new HashSet<StudentClass>();
            this.TeacherClassSubject = new HashSet<TeacherClassSubject>();
        }
    
        public string Id { get; set; }
        public Nullable<int> InstituteID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string GurdiansNumber { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public int GenderID { get; set; }
        public int BloodGroupID { get; set; }
        public int ReligionID { get; set; }
        public string Image { get; set; }
        public System.DateTime Date { get; set; }
        public string Password { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounting> Accounting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admission { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Institute> Institute { get; set; }
        public virtual Institute Institute1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogData> LogData { get; set; }
        public virtual Religion Religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendance> StudentAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherClassSubject> TeacherClassSubject { get; set; }
    }
}
