//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mass_Data_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClass
    {
        public int Id { get; set; }
        public string PersonId { get; set; }
        public int Roll { get; set; }
        public int ClassFee { get; set; }
        public int ClassID { get; set; }
        public System.DateTime Year { get; set; }
        public bool IsActive { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Person Person { get; set; }
    }
}
